FROM registry.access.redhat.com/ubi9/nginx-120

# Add application sources
ADD compliance-view/nginx.conf "${NGINX_CONF_PATH}"
ADD compliance-view/nginx-default-cfg/*.conf "${NGINX_DEFAULT_CONF_PATH}"
ADD compliance-view/nginx-cfg/*.conf "${NGINX_CONFIGURATION_PATH}"
ADD index.html .
ADD html/*.html .


# Run script uses standard ways to run the application
CMD nginx -g "daemon off;"
